// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfZs72XyW0faW5PFrCCKIAg0l3vUqDiBM',
    appId: '1:887678983320:web:bfef747e9a007ffe8244ed',
    messagingSenderId: '887678983320',
    projectId: 'doctor-oncall-portal',
    authDomain: 'doctor-oncall-portal.firebaseapp.com',
    storageBucket: 'doctor-oncall-portal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAPhPLkHe7RcljS1Hc6ownXOiPzuMKp94',
    appId: '1:887678983320:android:8a69822dcadc5ecf8244ed',
    messagingSenderId: '887678983320',
    projectId: 'doctor-oncall-portal',
    storageBucket: 'doctor-oncall-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5DrdVwmB2O632P3BxGdF5u9UijCYDnJU',
    appId: '1:887678983320:ios:7a50a15fc64cdaef8244ed',
    messagingSenderId: '887678983320',
    projectId: 'doctor-oncall-portal',
    storageBucket: 'doctor-oncall-portal.firebasestorage.app',
    iosBundleId: 'com.example.oncallDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5DrdVwmB2O632P3BxGdF5u9UijCYDnJU',
    appId: '1:887678983320:ios:7a50a15fc64cdaef8244ed',
    messagingSenderId: '887678983320',
    projectId: 'doctor-oncall-portal',
    storageBucket: 'doctor-oncall-portal.firebasestorage.app',
    iosBundleId: 'com.example.oncallDoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfZs72XyW0faW5PFrCCKIAg0l3vUqDiBM',
    appId: '1:887678983320:web:f03ece931045359c8244ed',
    messagingSenderId: '887678983320',
    projectId: 'doctor-oncall-portal',
    authDomain: 'doctor-oncall-portal.firebaseapp.com',
    storageBucket: 'doctor-oncall-portal.firebasestorage.app',
  );
}
